version: 0.2
env:
  parameter-store:
    DOCKER_INFLUXDB_INIT_PASSWORD: "DOCKER_INFLUXDB_INIT_PASSWORD"
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"

phases:
  install:
    commands:
      - cd ./frontend
      - npm install
      - cd ../backend
      - npm install
  pre_build:
    commands:
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - cd ./backend
      - npm run test
      - cd ../frontend
      - npm run test:unit
      - npm run test:coverage
  build:
    commands:
      - docker-compose build --no-cache
      - docker-compose up --timeout 30
  post_build:
    commands:
      - docker-compose down
      - docker-compose push