version: '3'
services:
  webapp:
    image:  danmillett/moniotor-front:1.0
    # build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=db0
    container_name: moniotor-webapp-1
  backend:
    image:  danmillett/moniotor-back:2.0
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    # env_file:
    #   - ./settings.env
    ports:
      - 8081:8081
    container_name: moniotor-backend-1
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=db0
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
      - DOCKER_INFLUXDB_INIT_ORG=nuig
    container_name: moniotor-influxdb-1
    # env_file:
    #   - ./settings.env
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - webapp